language: node_js
node_js:
- 10.15.3
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: rz+H6ooWNHmTrPTqkBqQ2zTf8EVSsD2hjUmoHc/jRuNXCgeO+PgGnlfzHYXa0k96BaILTKkYrIOYCHnbZT8CdF99Q1ESRcZkbg4uZ/DpEUeuqwSi4yPx4xTsrM7XexZDZT9hyuKOkKuZpBq6KAnfkr0q6b+bvXkSa3P2oGzeyLMkKo2xaD5igNiB9gXMVSXbW6d8XNmGBR3iHEOoiKL1FOiFi4sjLFj1qoZe2CcvIi0i7b5Zno+CZuPYGDLJKqd2yOB/Vu6PuMioAbLepIxvU/OrvOIwMhkDRPsC6oFMwq1KA79eNFOgaE88D3DA9zek/doyaqtKjsgWmHuOujr5NQ8JL4197Su3rQzN28Y4L27jkZ+K19+sKGMosxq3lKOHpWHk7jFnKb6L0K1eBzrAxmEV0TtRNVkudSTAVhEaqt1T0g1IrNvsiQ5sCFPqUl0nKYJUAIGfAfXP01B7Z5wV6APFYbMADuXBcKhNECDH5GNjk8D7Ribc2ZD4VsohUSrkTEI4nNKx++8A23kvgHHJzejtp4wcM4E+bP3cRw6FMmrFw7AyhxqAX6SZb9nx8LKc8V/XD54aPv0tIt6Ght/FzDWuJAB39vH+adC8Y/3p1UaePSiBgWgwrDzKjP+T9+IGf8JE2F+l7i6tAHy/Hsr9w+OTe1CmQIpqe89sadvHbuI=
  app: fell-product-store
  on:
    repo: FellRamos/Product-store
