language: node_js
node_js:
- 10.15.3
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: Kqfa6c5Q0V4NTYZQWBBa/lxqPWHmhQx9TXBHfhN1KThBDwD326ch7iT1vOXNSt/18rYVLGyvWBa9+aKkk8C8gCWfRKcMC8mtqu4XWiVnTiE82VI0JqJnaBaIWbYf+nMpHTlawWFQOFRP85vp7EKUPF1MlEI9Yfe+sz7PTqUT+fGaejSVqkhtfL/kYt3lf/U/Vy57qCR3MAPbNTeOoXtOOfZE7VPyL1r5SAnD1XUHIX551noUBtPqBcRLT7CKqtMzMdirtHluJT3PT1MFP84yI8BXMz5XCY9LMwCa4HKUMiU8vW6c61EwjkLRkEpY3L5ldIBnywO6win4XD77icbEwTPMwnfoh8J3/9HYKqbpym/+tYamY/YykLRVX9XOxmmkDV/sAnwaFeSkw9f2AwsDUXylyaNO2+ZNMLRJ4ERA+l1CHWX1Ha2e7lZ831kPNtAVxsJEm4zVHxzS4a3mp4yYG/JNC4XGYdo70Wl9j5fsCZNTOixs6sR/GWxQRqI6ngia8Cp7zr66a8MyBOriIehviNbIewZCyzPRYZSd1dj9sBI4Ck+f/wB1Y5fh+NQlAntV/sKKatiHadPH7xr3MP4aqhDp3qdGW7OnaRGdKHWe4CrkrLtUbWGRNYhQudPXHqA7JDPQ8iE+C/GZ0o3Sm8GCqvONIiKhJgzl/wOUMOnhTQI=
  app: fell-product-store
  on:
    repo: FellRamos/Product-store
